// Section metadata for the specimen page: numbering, copy, and the Figma node each
// section documents. Demo-only — not part of the published library.

export type SectionMeta = {
  id: string
  num: string
  kicker: string
  title: string
  lede: string
  figmaNode: string
  spec?: { dt: string; dd: string }[]
  tag?: string
}

export const SECTIONS: SectionMeta[] = [
  {
    id: 'tokens',
    num: '01',
    kicker: 'Foundation',
    title: 'Base tokens',
    lede: 'The variables every component is built from. Colors, typography, spacing, radii, elevation, and motion — sourced from the Figma library and exposed as CSS custom properties on `:root`.',
    figmaNode: '8:420',
    spec: [
      { dt: 'Source', dd: 'src/index.css' },
      { dt: 'Strategy', dd: 'CSS custom properties' },
      { dt: 'Scope', dd: 'global' },
    ],
  },
  {
    id: 'navigation',
    num: '02',
    kicker: 'Module',
    title: 'Navigation',
    lede: 'Primary surface for moving between Operator-platform sections. Desktop is a top-bar with brand + product label; mobile is a bottom-bar with stacked icon-on-pill labels.',
    figmaNode: '6140:3865 · 6072:2172',
    spec: [
      { dt: 'Active fill', dd: 'interaction-primary-focus' },
      { dt: 'Label style', dd: 'label-button (Inter 500)' },
      { dt: 'Breakpoints', dd: 'desktop · mobile' },
    ],
  },
  {
    id: 'sidebar',
    num: '03',
    kicker: 'Module',
    title: 'Side navigation',
    lede: 'Vertical primary navigation for shells with deeper navigation trees. Persistent rail with optional collapse to icons-only, one level of nested groups, and a user chip in the footer. Mobile collapses to a burger trigger that opens it as an overlay drawer.',
    figmaNode: '—',
    spec: [
      { dt: 'Width', dd: '264px · 72px collapsed' },
      { dt: 'Active state', dd: 'interaction-primary-focus + 3px rail' },
      { dt: 'Layouts', dd: 'desktop · mobile (drawer)' },
    ],
  },
  {
    id: 'kpi',
    num: '04',
    kicker: 'Module',
    title: 'KPI',
    lede: 'A single metric with optional secondary context. The 6-pixel top accent communicates state at a glance.',
    figmaNode: '6063:1279',
    spec: [
      { dt: 'Surface', dd: 'surface-light, border-medium' },
      { dt: 'Accent', dd: 'icon-* token per status' },
      { dt: 'Value type', dd: 'heading-3 / 20–24px' },
    ],
  },
  {
    id: 'buttons',
    num: '05',
    kicker: 'Component',
    title: 'Buttons',
    lede: 'Three styles, one motion vocabulary. Filled is the brand-default; outlined and text descend in emphasis.',
    figmaNode: '1:37',
    spec: [
      { dt: 'Variants', dd: 'filled · outlined · text' },
      { dt: 'Default size', dd: '48px / radius-l' },
      { dt: 'Focus ring', dd: 'interaction-primary-focus' },
    ],
  },
  {
    id: 'inputs',
    num: '06',
    kicker: 'Component',
    title: 'Input fields',
    lede: 'Label, optional leading/trailing icon, helper text, and an error state with a red focus halo.',
    figmaNode: '4011:1499',
    spec: [
      { dt: 'States', dd: 'default · hover · focus · error' },
      { dt: 'Padding', dd: 'm · 16px' },
      { dt: 'Helper', dd: 'body-s / 14–16px' },
    ],
  },
  {
    id: 'cards',
    num: '07',
    kicker: 'Module',
    title: 'Cards',
    lede: 'Title + subtitle, optional trailing slot, and a body that accepts arbitrary children. Floating adds elevation-l.',
    figmaNode: '6064:722 · 6145:11695',
    spec: [
      { dt: 'Padding', dd: 'm · 16px' },
      { dt: 'Radius', dd: 'xl · 16px' },
      { dt: 'Variants', dd: 'floating yes · no' },
    ],
  },
  {
    id: 'context-menu',
    num: '08',
    kicker: 'Module',
    title: 'Context menu',
    lede: 'A 320-px floating panel for object-scoped actions. Items support icon, disabled, and destructive emphasis.',
    figmaNode: '6063:1658',
    spec: [
      { dt: 'Surface', dd: 'surface-page · elevation-l' },
      { dt: 'Width', dd: '320px' },
      { dt: 'Item radius', dd: 'm · 8px' },
    ],
  },
  {
    id: 'sidesheet',
    num: '09',
    kicker: 'Module',
    title: 'Sidesheet',
    lede: 'A 480-px panel that slides in from a viewport edge. Navigation row, header with status pill, scrolling body, and a sticky action footer.',
    figmaNode: '6103:2880',
    spec: [
      { dt: 'Width', dd: '480px' },
      { dt: 'Surface', dd: 'surface-light · elevation-l' },
      { dt: 'Footer', dd: 'primary + secondary action' },
    ],
  },
  {
    id: 'messages',
    num: '10',
    kicker: 'Module',
    title: 'Messages',
    lede: 'Inline or floating, in four semantic states. Each state shifts background, border, icon, and text together to keep the read fluid.',
    figmaNode: '6052:1186',
    spec: [
      { dt: 'States', dd: 'neutral · success · warning · error' },
      { dt: 'Types', dd: 'inline · floating' },
      { dt: 'Roles', dd: 'status · alert' },
    ],
  },
  {
    id: 'progress',
    num: '11',
    kicker: 'Component',
    title: 'Progress bars',
    lede: 'A thin 8-pixel rail with optional label and percentage. Tone tracks the underlying KPI status.',
    figmaNode: '6025:562',
    spec: [
      { dt: 'Height', dd: '8px' },
      { dt: 'Tones', dd: 'default · blue · orange · neutral' },
      { dt: 'Motion', dd: 'width transitions on update' },
    ],
  },
  {
    id: 'checkbox',
    num: '12',
    kicker: 'Component',
    title: 'Checkbox',
    lede: 'Inline option, plus border-left and border-right card layouts for selection grids.',
    figmaNode: '6029:687',
    spec: [
      { dt: 'States', dd: 'default · focus · error · disabled' },
      { dt: 'Checked', dd: 'true · false · indeterminate' },
      { dt: 'Layouts', dd: 'inline · border-left · border-right' },
    ],
    tag: 'wip',
  },
  {
    id: 'radio',
    num: '13',
    kicker: 'Component',
    title: 'Radio button',
    lede: 'Mirrors the Checkbox layouts and states with a circular indicator that scales in on selection.',
    figmaNode: '6059:1143',
    spec: [
      { dt: 'States', dd: 'default · focus · error · disabled' },
      { dt: 'Layouts', dd: 'inline · border-left · border-right' },
      { dt: 'Group via', dd: 'native name attribute' },
    ],
  },
  {
    id: 'form',
    num: '14',
    kicker: 'Module',
    title: 'Form',
    lede: 'A composition layer over Inputs, Checkbox, Radio, and Button. Sections carry a Roman-numeral step, a title, and a description; the body holds fields and an action footer.',
    figmaNode: '—',
    spec: [
      { dt: 'Layout', dd: '132px head · 1fr body' },
      { dt: 'Validation', dd: 'errorText prop per field' },
      { dt: 'Library', dd: 'agnostic · works with RHF Controller' },
    ],
  },
  {
    id: 'table',
    num: '15',
    kicker: 'Module',
    title: 'Data table',
    lede: 'Sortable ledger built on @tanstack/react-table. Mono-caps headers, dashed row rules, tabular numerics, and Pill-rendered status cells.',
    figmaNode: '—',
    spec: [
      { dt: 'Engine', dd: '@tanstack/react-table v8' },
      { dt: 'Sorting', dd: 'click header · aria-sort' },
      { dt: 'Cell meta', dd: 'numeric · align' },
    ],
  },
  {
    id: 'avatar',
    num: '16',
    kicker: 'Component',
    title: 'Avatar',
    lede: 'A person or entity marker. Renders an image when available and falls back to initials derived from the name — across five sizes and two shapes.',
    figmaNode: '—',
    spec: [
      { dt: 'Sizes', dd: 'xs · s · m · l · xl' },
      { dt: 'Shapes', dd: 'circle · square' },
      { dt: 'Fallback', dd: 'initials from name' },
    ],
  },
  {
    id: 'select',
    num: '17',
    kicker: 'Component',
    title: 'Select',
    lede: 'A single-choice dropdown built on Base UI. The trigger mirrors the input field; the popup matches its width and checks the active option.',
    figmaNode: '—',
    spec: [
      { dt: 'Trigger', dd: '48px · matches Input' },
      { dt: 'States', dd: 'default · open · error · disabled' },
      { dt: 'Naming', dd: 'aria-label / labelledby' },
    ],
  },
  {
    id: 'combobox',
    num: '18',
    kicker: 'Component',
    title: 'Combobox',
    lede: 'Type-ahead autocomplete over a list of options. Filters as you type and surfaces an empty-state message when nothing matches.',
    figmaNode: '—',
    spec: [
      { dt: 'Engine', dd: 'Base UI Autocomplete' },
      { dt: 'Empty state', dd: 'configurable message' },
      { dt: 'Popup', dd: 'anchor-width · 320px max' },
    ],
  },
  {
    id: 'number-field',
    num: '19',
    kicker: 'Component',
    title: 'Number field',
    lede: 'A numeric input with decrement / increment steppers, min–max clamping, and Intl number formatting. Keyboard supports small and large steps.',
    figmaNode: '—',
    spec: [
      { dt: 'Steppers', dd: '44px · ±step' },
      { dt: 'Formatting', dd: 'Intl.NumberFormat' },
      { dt: 'States', dd: 'default · error · disabled' },
    ],
  },
  {
    id: 'slider',
    num: '20',
    kicker: 'Component',
    title: 'Slider',
    lede: 'A single-value range control with a 6-pixel track, draggable thumb, and optional inline value read-out. Commits on pointer-up or keyboard.',
    figmaNode: '—',
    spec: [
      { dt: 'Track', dd: '6px · border-medium' },
      { dt: 'Thumb', dd: '20px · primary ring' },
      { dt: 'Tones', dd: 'default · error' },
    ],
  },
  {
    id: 'toggle',
    num: '21',
    kicker: 'Component',
    title: 'Toggle',
    lede: 'A two-state pressable button, standalone or grouped into a segmented control. The group behaves as a single- or multi-select toolbar.',
    figmaNode: '—',
    spec: [
      { dt: 'Sizes', dd: 's · m' },
      { dt: 'Group', dd: 'single · multi-select' },
      { dt: 'Role', dd: 'button · toolbar' },
    ],
  },
  {
    id: 'switch',
    num: '22',
    kicker: 'Component',
    title: 'Switch',
    lede: 'A binary on / off control with an optional inline label and secondary text. The thumb slides on a track that shifts to the primary tone when on.',
    figmaNode: '—',
    spec: [
      { dt: 'Track', dd: '40 × 24px' },
      { dt: 'States', dd: 'on · off · error · disabled' },
      { dt: 'Label', dd: 'optional · inline' },
    ],
  },
  {
    id: 'tabs',
    num: '23',
    kicker: 'Module',
    title: 'Tabs',
    lede: 'Switch between sibling panels with a sliding active indicator. Horizontal or vertical, with optional per-tab icons.',
    figmaNode: '—',
    spec: [
      { dt: 'Orientations', dd: 'horizontal · vertical' },
      { dt: 'Indicator', dd: 'animated · 2px' },
      { dt: 'Per tab', dd: 'icon · disabled' },
    ],
  },
  {
    id: 'accordion',
    num: '24',
    kicker: 'Module',
    title: 'Accordion',
    lede: 'A stack of headers that expand to reveal content. Single-open by default; opt into multiple. Panel height animates on toggle.',
    figmaNode: '—',
    spec: [
      { dt: 'Mode', dd: 'single · multiple' },
      { dt: 'Motion', dd: 'height · 200ms' },
      { dt: 'Per item', dd: 'disabled' },
    ],
  },
  {
    id: 'collapsible',
    num: '25',
    kicker: 'Component',
    title: 'Collapsible',
    lede: 'A single trigger that shows or hides a region of content, with an animated height transition and an optional chevron affordance.',
    figmaNode: '—',
    spec: [
      { dt: 'Motion', dd: 'height · 200ms' },
      { dt: 'Chevron', dd: 'optional' },
      { dt: 'State', dd: 'open · closed · disabled' },
    ],
  },
  {
    id: 'breadcrumb',
    num: '26',
    kicker: 'Component',
    title: 'Breadcrumb',
    lede: 'A hierarchical trail to the current page. Links and buttons are interactive; the final crumb is marked as the current location.',
    figmaNode: '—',
    spec: [
      { dt: 'Separator', dd: 'chevron · custom' },
      { dt: 'Current', dd: 'aria-current=page' },
      { dt: 'Items', dd: 'link · button · text' },
    ],
  },
  {
    id: 'pagination',
    num: '27',
    kicker: 'Component',
    title: 'Pagination',
    lede: 'Page navigation with previous / next controls and a truncated page range that keeps the first, last, and current pages in view.',
    figmaNode: '—',
    spec: [
      { dt: 'Range', dd: 'sibling-aware ellipses' },
      { dt: 'Cell', dd: '40px · active fill' },
      { dt: 'Controls', dd: 'prev · next' },
    ],
  },
  {
    id: 'separator',
    num: '28',
    kicker: 'Component',
    title: 'Separator',
    lede: 'A one-pixel divider for splitting content. Horizontal or vertical, with an optional centered label on the horizontal variant.',
    figmaNode: '—',
    spec: [
      { dt: 'Orientations', dd: 'horizontal · vertical' },
      { dt: 'Weight', dd: '1px · border-light' },
      { dt: 'Label', dd: 'optional · centered' },
    ],
  },
  {
    id: 'popover',
    num: '29',
    kicker: 'Module',
    title: 'Popover',
    lede: 'A floating surface anchored to a trigger, with optional title, description, and pointer arrow. Non-modal by default.',
    figmaNode: '—',
    spec: [
      { dt: 'Surface', dd: 'surface-light · elevation-l' },
      { dt: 'Placement', dd: 'side · align · offset' },
      { dt: 'Arrow', dd: 'optional' },
    ],
  },
  {
    id: 'dialog',
    num: '30',
    kicker: 'Module',
    title: 'Dialog',
    lede: 'A centered modal for focused tasks. Title, optional description, arbitrary body, and a footer of primary / secondary actions that close on click.',
    figmaNode: '—',
    spec: [
      { dt: 'Sizes', dd: 's · m · l' },
      { dt: 'Surface', dd: 'surface-light · elevation-l' },
      { dt: 'Actions', dd: 'primary · secondary' },
    ],
  },
  {
    id: 'alert-dialog',
    num: '31',
    kicker: 'Module',
    title: 'Alert dialog',
    lede: 'A compact confirmation modal for consequential actions. Cancel and confirm are required; the danger tone renders a destructive confirm.',
    figmaNode: '—',
    spec: [
      { dt: 'Width', dd: '400px' },
      { dt: 'Tones', dd: 'default · danger' },
      { dt: 'Dismiss', dd: 'requires a choice' },
    ],
  },
  {
    id: 'skeleton',
    num: '32',
    kicker: 'Component',
    title: 'Skeleton',
    lede: 'A pulsing placeholder for content that is still loading. Text, rectangular, and circular variants; text can render multiple lines.',
    figmaNode: '—',
    spec: [
      { dt: 'Variants', dd: 'text · rectangular · circular' },
      { dt: 'Motion', dd: 'animate-pulse' },
      { dt: 'Text', dd: 'multi-line · shortened last' },
    ],
  },
  {
    id: 'textarea',
    num: '33',
    kicker: 'Component',
    title: 'Textarea',
    lede: 'A multi-line text control that mirrors the Input field. Label, helper text, and an error state that swaps the border and focus halo to negative. The resize affordance is configurable.',
    figmaNode: '—',
    spec: [
      { dt: 'Resize', dd: 'none · vertical · horizontal · both' },
      { dt: 'Min height', dd: '96px · rows 4' },
      { dt: 'States', dd: 'default · error · disabled' },
    ],
  },
  {
    id: 'toast',
    num: '34',
    kicker: 'Module',
    title: 'Toast',
    lede: 'Transient notifications stacked at the viewport corner, fired imperatively. Five tones, an optional action, and auto-dismiss. Wrap the app once in `ToastProvider`, then call `useToast()` from anywhere below.',
    figmaNode: '—',
    spec: [
      { dt: 'Tones', dd: 'neutral · success · error · warning · info' },
      { dt: 'Viewport', dd: 'fixed bottom-right · 400px' },
      { dt: 'API', dd: 'ToastProvider + useToast()' },
    ],
  },
  {
    id: 'tooltip',
    num: '35',
    kicker: 'Component',
    title: 'Tooltip',
    lede: 'A small label revealed on hover or focus, anchored to its trigger with an optional pointer arrow. Inverted surface, configurable open / close delays, and four placements. Supplemental only — never the sole label for a control.',
    figmaNode: '3abda8 (set)',
    spec: [
      { dt: 'Surface', dd: 'surface-strong · inverted text' },
      { dt: 'Placement', dd: 'side · align · offset' },
      { dt: 'Delay', dd: 'open 200ms · close 0ms' },
    ],
  },
  {
    id: 'menu',
    num: '36',
    kicker: 'Module',
    title: 'Menu',
    lede: 'A click-triggered dropdown built on Base UI. The richer sibling of Context menu — groups with labels, checkbox and single-select radio items, nested submenus, and an optional pointer arrow, driven by a recursive items model.',
    figmaNode: '—',
    spec: [
      { dt: 'Items', dd: 'action · checkbox · radio · submenu' },
      { dt: 'Groups', dd: 'label · separator' },
      { dt: 'Scroll', dd: 'maxHeight · keyboard-aware' },
    ],
  },
  {
    id: 'toolbar',
    num: '37',
    kicker: 'Module',
    title: 'Toolbar',
    lede: 'A roving-focus container for grouped controls. Arrow keys move between items while only one stays in the tab order. Buttons, groups, separators, links, and a search input, at two densities.',
    figmaNode: '—',
    spec: [
      { dt: 'Parts', dd: 'button · group · separator · input' },
      { dt: 'Density', dd: 'comfortable · compact' },
      { dt: 'Focus', dd: 'roving · arrow keys' },
    ],
  },
  {
    id: 'scroll-area',
    num: '38',
    kicker: 'Component',
    title: 'Scroll area',
    lede: 'A styled, cross-browser scrollbar for long lists and panels. The thin tokenised thumb auto-hides when idle and appears on hover or scroll, with an always-visible variant.',
    figmaNode: '—',
    spec: [
      { dt: 'Orientation', dd: 'vertical · horizontal · both' },
      { dt: 'Thumb', dd: 'hover · always' },
      { dt: 'Clip', dd: 'maxHeight' },
    ],
  },
  {
    id: 'calendar',
    num: '39',
    kicker: 'Module',
    title: 'Calendar',
    lede: 'A tokenised month grid on react-day-picker. Single, multiple, or range selection with a banded middle and round endpoints, a today ring, multi-month layout, and dropdown captions.',
    figmaNode: '—',
    spec: [
      { dt: 'Modes', dd: 'single · multiple · range' },
      { dt: 'Today', dd: 'ring · never fights selected' },
      { dt: 'Layout', dd: 'numberOfMonths · dropdown caption' },
    ],
  },
  {
    id: 'date-picker',
    num: '40',
    kicker: 'Module',
    title: 'Date picker',
    lede: 'A single-date field that opens a Calendar in a Popover. Controlled or uncontrolled, with min–max bounds, a clear affordance, and full Form/Field binding so it lights up like an Input.',
    figmaNode: '—',
    spec: [
      { dt: 'Trigger', dd: '48px · matches Input' },
      { dt: 'Bounds', dd: 'minDate · maxDate · disabledDates' },
      { dt: 'States', dd: 'default · error · disabled · clearable' },
    ],
  },
]

const SECTION_BY_ID = Object.fromEntries(SECTIONS.map((s) => [s.id, s])) as Record<string, SectionMeta>
export const sec = (id: string): SectionMeta => SECTION_BY_ID[id]
